import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import NextUiProviders from '@/lib/providers/nextui'
import Navbars from '@/components/Layouts/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Huy's",
  description: "Generated by Huynm's nextjs"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} w-full bg-gradient-to-r from-slate-900 to-slate-700 text-white`}>
        <NextUiProviders>
          <section className='flex flex-col'>
            <Navbars />
            <div className=''>{children}</div>
          </section>
        </NextUiProviders>
      </body>
    </html>
  )
}
